ALTER TYPE "AuditEventType" ADD VALUE 'EMPLOYEE_DIRECTORY_EMPLOYEE_ADDED';
ALTER TYPE "AuditEventType" ADD VALUE 'EMPLOYEE_DIRECTORY_EMPLOYEE_UPDATED';
ALTER TYPE "AuditEventType" ADD VALUE 'EMPLOYEE_DIRECTORY_EMPLOYEE_REMOVED';
ALTER TYPE "AuditEventType" ADD VALUE 'EMPLOYEE_DIRECTORY_EMPLOYEE_REACTIVATED';

ALTER TABLE "OrganizationMembership"
ADD COLUMN "removedAt" TIMESTAMP(3);

ALTER TABLE "EmployeeDirectorySyncRun"
ADD COLUMN "reactivatedCount" INTEGER NOT NULL DEFAULT 0;
