import "server-only";

import {
  parseEnvironment,
  parseTestnetEnvironment,
  type Environment,
  type TestnetEnvironment,
} from "@/infrastructure/config/environment-schema";

let cachedEnvironment: Environment | undefined;

export function validateEnvironment(): Environment {
  if (cachedEnvironment) return cachedEnvironment;

  cachedEnvironment = parseEnvironment({
    DATABASE_URL: process.env.DATABASE_URL,
    APP_URL: process.env.APP_URL,
    RATE_LIMIT_ENABLED: process.env.RATE_LIMIT_ENABLED,
    RATE_LIMIT_HASH_SECRET: process.env.RATE_LIMIT_HASH_SECRET,
    RATE_LIMIT_TRUST_PROXY: process.env.RATE_LIMIT_TRUST_PROXY,
    RATE_LIMIT_TRUSTED_PROXY_HOPS: process.env.RATE_LIMIT_TRUSTED_PROXY_HOPS,
    RATE_LIMIT_WINDOW_SECONDS: process.env.RATE_LIMIT_WINDOW_SECONDS,
    RATE_LIMIT_AUTH_MAX: process.env.RATE_LIMIT_AUTH_MAX,
    RATE_LIMIT_PUBLIC_MAX: process.env.RATE_LIMIT_PUBLIC_MAX,
    RATE_LIMIT_SENSITIVE_MAX: process.env.RATE_LIMIT_SENSITIVE_MAX,
    RATE_LIMIT_ADMIN_MAX: process.env.RATE_LIMIT_ADMIN_MAX,
    RATE_LIMIT_EXPENSIVE_MAX: process.env.RATE_LIMIT_EXPENSIVE_MAX,
    ARC_RECONCILIATION_ENABLED: process.env.ARC_RECONCILIATION_ENABLED,
    ARC_RECONCILIATION_RPC_URL: process.env.ARC_RECONCILIATION_RPC_URL,
    ARC_RECONCILIATION_START_BLOCK: process.env.ARC_RECONCILIATION_START_BLOCK,
    ARC_RECONCILIATION_CONFIRMATIONS:
      process.env.ARC_RECONCILIATION_CONFIRMATIONS,
    ARC_RECONCILIATION_BLOCK_RANGE: process.env.ARC_RECONCILIATION_BLOCK_RANGE,
    ARC_RECONCILIATION_REORG_WINDOW:
      process.env.ARC_RECONCILIATION_REORG_WINDOW,
    ARC_RECONCILIATION_MAX_RANGES: process.env.ARC_RECONCILIATION_MAX_RANGES,
    ARC_RECONCILIATION_RPC_RETRIES: process.env.ARC_RECONCILIATION_RPC_RETRIES,
    ARC_RECONCILIATION_STALE_AFTER_MINUTES:
      process.env.ARC_RECONCILIATION_STALE_AFTER_MINUTES,
    OBSERVABILITY_FAILURE_ALERT_THRESHOLD:
      process.env.OBSERVABILITY_FAILURE_ALERT_THRESHOLD,
    OBSERVABILITY_UNMATCHED_EVENT_ALERT_THRESHOLD:
      process.env.OBSERVABILITY_UNMATCHED_EVENT_ALERT_THRESHOLD,
    ARC_RECONCILIATION_CRON_SECRET: process.env.ARC_RECONCILIATION_CRON_SECRET,
    LOAN_DECISION_PROVIDER: process.env.LOAN_DECISION_PROVIDER,
    EMPLOYER_ACTION_PROVIDER: process.env.EMPLOYER_ACTION_PROVIDER,
    ERP_NEXT_ALLOW_LOCAL_HTTP: process.env.ERP_NEXT_ALLOW_LOCAL_HTTP,
    ERP_NEXT_SYNC_ENABLED: process.env.ERP_NEXT_SYNC_ENABLED,
    ERP_NEXT_SYNC_INTERVAL_MINUTES: process.env.ERP_NEXT_SYNC_INTERVAL_MINUTES,
    ERP_NEXT_SYNC_STALE_AFTER_MINUTES:
      process.env.ERP_NEXT_SYNC_STALE_AFTER_MINUTES,
    ERP_NEXT_SYNC_PAGE_SIZE: process.env.ERP_NEXT_SYNC_PAGE_SIZE,
    ERP_NEXT_SYNC_MAX_PAGES: process.env.ERP_NEXT_SYNC_MAX_PAGES,
    ERP_NEXT_SYNC_CRON_SECRET: process.env.ERP_NEXT_SYNC_CRON_SECRET,
    ERP_NEXT_CREDENTIALS_JSON: process.env.ERP_NEXT_CREDENTIALS_JSON,
  });
  return cachedEnvironment;
}

export function validateTestnetEnvironment(): TestnetEnvironment {
  return parseTestnetEnvironment({
    ARC_CHAIN_ID: process.env.ARC_CHAIN_ID,
    ARC_RPC_URL: process.env.ARC_RPC_URL,
    ARC_USDC_ADDRESS: process.env.ARC_USDC_ADDRESS,
    NEXT_PUBLIC_ARC_LENDING_CONTRACT_ADDRESS:
      process.env.NEXT_PUBLIC_ARC_LENDING_CONTRACT_ADDRESS,
    NEXT_PUBLIC_CIRCLE_CLIENT_KEY: process.env.NEXT_PUBLIC_CIRCLE_CLIENT_KEY,
    NEXT_PUBLIC_CIRCLE_CLIENT_URL: process.env.NEXT_PUBLIC_CIRCLE_CLIENT_URL,
    ARC_BORROW_AUTHORIZER_PRIVATE_KEY:
      process.env.ARC_BORROW_AUTHORIZER_PRIVATE_KEY,
  });
}
